spring:
# 数据库链接
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: pg1105
    url: jdbc:postgresql://localhost:5432/now_admin?currentSchema=admin


# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:com.now.admin.**.mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: deleted_flag
      logic-delete-value: -1

# JWT配置
secret:
  # RSA私钥（用于签名Token）- 请使用RsaUtil生成真实密钥对
  private-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC6ph0V5Zmm4wMCXsp8s+Sw0jbHHL1lzxSx8pWhxhfGW962jh8GfLq0FFLiyChKfe5nKTLzMatmtYNxMVVcZlBdr9UE+ObP9MJFBdyTqre7D6O94RodVUqMMGjPK2D2IjyVJR2ujK1Aty+wMw9yfGl+/lNkVO06cEa+OjiEOlVZv00bgL6OIntTC8PpB175qXagTKFSJuzUn2pz1d6iA8feTxHhshj9ovoPbniIuMH9oPFctKGBYQmQHZQ/XgvvbdvBOxl7LIIlKghPZaISJxz7f4oubCjsEYVL7rN3lsCReKIjtHM4aO0mIwbF4hG/AoVzxUWoOclY5SM9wFX+U6k/AgMBAAECggEAEWa3Q3lab+KuPyRTQHkNEycmED4vsjQyO7zgEmsDgGzEQMTTQ6mRRoS2jYoXp4pCFcATjfTNhA/cJ0twJ+MqDvH7rDEAY9bv3buEKwg5hOkaXPOFmcJ/5r4Ep3vl2Eys1ULWl5Vp+aSaf5TjFctfkoVnhO0eCNq63bVT25AMsQcp8MVB6NTBScNTlcPl5maPqkLAAqU30ul/af/+BYUI/OxFRPw6HKM4jyr9hg8ww9+vHNiaTDHxijeQVE7FX5FIIIgYanf/hHkuf4HA20FOyL9AU5zrdX/ZG5ga09Y8bh9wRQUx3D1Jpikm520e8xBaD9k4A9Ldi27EjPeTLO88IQKBgQDp9S1W5zCZHodGNT/82Du0o53rKkP+MfKRUV9QnqOaQJAMgUIKn/GQ/oWiW3NRZk5st2rJCwVGy1bJdF/U909q2MTaxec82S7KrNAxNx1H6O7jiGAsL8DNyH32TxXB5uHhiUTN7c6izUxgB6haAqesvCmWZg0naAeufHSFsAOhqQKBgQDMO+Uu6vXRLDIlVZzUFQHof8617gPYQZU0KMXTaueSrV0N3xN/iiImrrfew5K//HJR16mT4gcNl7s0jNpyXf0aRQxenHMGQvxfi0cTS70Sk8dTUXGBHg08Go85LihTiamBpwcymNIwDs/nKKWMfR4L6KjYscFQpS7oUoLcxTQUpwKBgARxyOu2tqCiCNXXmyCVhwTWeuCFzAbfMgl6r0Hb0aXThikGp5eGFFO50hYUgKtSMzkzfs7U68O9hyeKk2t7S0HvXkX9rnfkdFQbVlUpA+Bi127xH0qXmaUPIv1z4Sju1umu7uSumNdU6ReF7bfQBxlr9apKxAM0obi52ojToC4JAoGAbeTMrTJAkwz07qHigTvMiw46bCpmZzbi0e4ehGRBtusR5yThmP764VWiGnuhuyxbVy50UN6ObQH3+Y7Q/DkWt8vvm/kS64ufwMlwtTFLy3M5DdwE9zT0aiLgbiQoDstEKj914APbFYDi3b9BVRb90+qc7/y1yG8ZjmjXgXObUoECgYAGoK3TwrKKYowafG4kK2KoaTS0jsLrUUPZxP1AHg3SooY9EM8aPfkAXnSTfba2/jc54jN6ZVUO/4HEhgow5lM1cNPvu/aa0TaxQJzArr2gAIykHTEFe9DyHZKoeGnE8aaCc/RQSrZn6QS0hzYgYEdGF6V5P5fTagg3ukEENfsasQ==

  # RSA公钥（用于验证Token）
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuqYdFeWZpuMDAl7KfLPksNI2xxy9Zc8UsfKVocYXxlveto4fBny6tBRS4sgoSn3uZyky8zGrZrWDcTFVXGZQXa/VBPjmz/TCRQXck6q3uw+jveEaHVVKjDBozytg9iI8lSUdroytQLcvsDMPcnxpfv5TZFTtOnBGvjo4hDpVWb9NG4C+jiJ7UwvD6Qde+al2oEyhUibs1J9qc9XeogPH3k8R4bIY/aL6D254iLjB/aDxXLShgWEJkB2UP14L723bwTsZeyyCJSoIT2WiEicc+3+KLmwo7BGFS+6zd5bAkXiiI7RzOGjtJiMGxeIRvwKFc8VFqDnJWOUjPcBV/lOpPwIDAQAB

  # Token过期时间（毫秒）10小时
  expiration: 36000000
  # Token刷新时间（毫秒）2小时内可刷新
  refresh-expiration: 7200000
  # 是否启用外部文件加载密钥（生产环境建议启用）
  use-external-file: false
  # 外部密钥文件路径（当use-external-file=true时生效）
  key-file-path: ./keys
